/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet;
import com.sun.istack.internal.logging.Logger;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import sun.util.logging.PlatformLogger;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author toshiba
 */
public class Etudiant extends javax.swing.JFrame {

    private ImageIcon format=null;
    String fname=null;
    String imagePth=null;
    byte[] pimage=null;
   
     Connection con=null;
     boolean contactIsCreated=true;
    public Etudiant() {
        con=ConnexionMysql.connect();
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelFormulaire = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelAnnee_Etude = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelFiliere = new javax.swing.JLabel();
        jLabelDate_Naiss = new javax.swing.JLabel();
        jLabelFaculte = new javax.swing.JLabel();
        jLabelMatricule = new javax.swing.JLabel();
        jTextFieldMatricule = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldFiliere = new javax.swing.JTextField();
        jTextFieldAnnee_Etude = new javax.swing.JTextField();
        jTextFieldFaculte = new javax.swing.JTextField();
        jButtonSup = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jButtonAjout = new javax.swing.JButton();
        jButtonImport = new javax.swing.JButton();
        jPanelPhoto = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        JLabelphoto = new javax.swing.JLabel();
        jPanelCarte = new javax.swing.JPanel();
        jLabelNom1 = new javax.swing.JLabel();
        jLabelPrenom1 = new javax.swing.JLabel();
        jLabelDate_Naiss1 = new javax.swing.JLabel();
        jLabelFiliere1 = new javax.swing.JLabel();
        jLabelFaculte1 = new javax.swing.JLabel();
        jLabelAnnee_Etude1 = new javax.swing.JLabel();
        jLabelMatricule1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPhotoCarte = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNomCarte = new javax.swing.JLabel();
        jLabelPrenomCarte = new javax.swing.JLabel();
        jLabelDate_naissCarte = new javax.swing.JLabel();
        jLabelFiliereCarte = new javax.swing.JLabel();
        jLabelFaculteCarte = new javax.swing.JLabel();
        jLabelAnnee_etudeCarte = new javax.swing.JLabel();
        jLabelMatriculeCarte = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonImprime = new javax.swing.JButton();
        jLabelfleche = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(240, 240, 240));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet/um.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestion des étudiants");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanelFormulaire.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jLabelNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNom.setText("Nom: ");

        jTextFieldNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNom.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jLabelAnnee_Etude.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAnnee_Etude.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAnnee_Etude.setText("Année d'étude:  ");

        jLabelPrenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrenom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPrenom.setText("Prénom: ");

        jLabelFiliere.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFiliere.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFiliere.setText("Filiére: ");

        jLabelDate_Naiss.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDate_Naiss.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDate_Naiss.setText("Date Naissance: ");

        jLabelFaculte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFaculte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFaculte.setText("Faculté: ");

        jLabelMatricule.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMatricule.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMatricule.setText("Matricule: ");

        jTextFieldMatricule.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldMatricule.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculeActionPerformed(evt);
            }
        });

        jTextFieldPrenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPrenom.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });

        jTextFieldFiliere.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFiliere.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldFiliere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiliereActionPerformed(evt);
            }
        });

        jTextFieldAnnee_Etude.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldAnnee_Etude.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldAnnee_Etude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnnee_EtudeActionPerformed(evt);
            }
        });

        jTextFieldFaculte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFaculte.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldFaculte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFaculteActionPerformed(evt);
            }
        });

        jButtonSup.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSup.setForeground(new java.awt.Color(240, 240, 240));
        jButtonSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet/supprimer.gif"))); // NOI18N
        jButtonSup.setText("Supprimer");
        jButtonSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupActionPerformed(evt);
            }
        });

        jButtonMod.setBackground(new java.awt.Color(0, 51, 204));
        jButtonMod.setForeground(new java.awt.Color(240, 240, 240));
        jButtonMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet/modifier.gif"))); // NOI18N
        jButtonMod.setText("Modifier");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonAjout.setBackground(new java.awt.Color(0, 153, 51));
        jButtonAjout.setForeground(new java.awt.Color(240, 240, 240));
        jButtonAjout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet/ajouter.gif"))); // NOI18N
        jButtonAjout.setText("Ajouter");
        jButtonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutActionPerformed(evt);
            }
        });

        jButtonImport.setBackground(new java.awt.Color(153, 102, 0));
        jButtonImport.setForeground(new java.awt.Color(240, 240, 240));
        jButtonImport.setText("Importer photo");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        jPanelPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanelPhoto.setPreferredSize(new java.awt.Dimension(150, 150));

        jPanel5.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JLabelphoto.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanelPhotoLayout = new javax.swing.GroupLayout(jPanelPhoto);
        jPanelPhoto.setLayout(jPanelPhotoLayout);
        jPanelPhotoLayout.setHorizontalGroup(
            jPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhotoLayout.createSequentialGroup()
                .addComponent(JLabelphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );
        jPanelPhotoLayout.setVerticalGroup(
            jPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhotoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(164, 164, 164))
            .addComponent(JLabelphoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFormulaireLayout = new javax.swing.GroupLayout(jPanelFormulaire);
        jPanelFormulaire.setLayout(jPanelFormulaireLayout);
        jPanelFormulaireLayout.setHorizontalGroup(
            jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormulaireLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSup)
                    .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelAnnee_Etude, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFaculte, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDate_Naiss, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFormulaireLayout.createSequentialGroup()
                        .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldAnnee_Etude, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                .addComponent(jTextFieldMatricule)
                                .addComponent(jTextFieldFaculte)
                                .addComponent(jTextFieldFiliere)
                                .addComponent(jTextFieldPrenom)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormulaireLayout.createSequentialGroup()
                        .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonImport, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFormulaireLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFormulaireLayout.setVerticalGroup(
            jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormulaireLayout.createSequentialGroup()
                .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormulaireLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanelFormulaireLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addComponent(jLabelDate_Naiss, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFaculte, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFaculte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnnee_Etude, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnnee_Etude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonImport, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanelFormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjout)
                    .addComponent(jButtonMod)
                    .addComponent(jButtonSup))
                .addGap(80, 80, 80))
        );

        jPanelCarte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jLabelNom1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNom1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNom1.setText("Nom: ");

        jLabelPrenom1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrenom1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPrenom1.setText("Prénom: ");

        jLabelDate_Naiss1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDate_Naiss1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDate_Naiss1.setText("Date Naissance: ");

        jLabelFiliere1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFiliere1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFiliere1.setText("Filiére: ");

        jLabelFaculte1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFaculte1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFaculte1.setText("Faculté: ");

        jLabelAnnee_Etude1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAnnee_Etude1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAnnee_Etude1.setText("Année d'étude:  ");

        jLabelMatricule1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMatricule1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMatricule1.setText("Matricule: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPhotoCarte, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPhotoCarte, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Carte d'étudiant");

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet/um.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(135, 135, 135)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelNomCarte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomCarte.setText("Votre Nom");

        jLabelPrenomCarte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrenomCarte.setText("Votre Prénom");

        jLabelDate_naissCarte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDate_naissCarte.setText("Votre Date Naissance");

        jLabelFiliereCarte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFiliereCarte.setText("Votre Filiére");

        jLabelFaculteCarte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFaculteCarte.setText("Votre Faculté");

        jLabelAnnee_etudeCarte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAnnee_etudeCarte.setText("Votre Année d'étude");

        jLabelMatriculeCarte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMatriculeCarte.setText("Votre Matricule");

        javax.swing.GroupLayout jPanelCarteLayout = new javax.swing.GroupLayout(jPanelCarte);
        jPanelCarte.setLayout(jPanelCarteLayout);
        jPanelCarteLayout.setHorizontalGroup(
            jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCarteLayout.createSequentialGroup()
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAnnee_Etude1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFaculte1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFiliere1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCarteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAnnee_etudeCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCarteLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelFiliereCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFaculteCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCarteLayout.createSequentialGroup()
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDate_Naiss1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrenomCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDate_naissCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCarteLayout.createSequentialGroup()
                        .addComponent(jLabelMatricule1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMatriculeCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCarteLayout.setVerticalGroup(
            jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarteLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCarteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomCarte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPrenomCarte)
                            .addComponent(jLabelPrenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDate_Naiss1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDate_naissCarte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFiliere1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFiliereCarte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFaculte1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFaculteCarte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnnee_Etude1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnnee_etudeCarte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMatricule1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMatriculeCarte))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jButtonImprime.setBackground(new java.awt.Color(255, 153, 51));
        jButtonImprime.setForeground(new java.awt.Color(240, 240, 240));
        jButtonImprime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet/imprimente.gif"))); // NOI18N
        jButtonImprime.setText("Imprimer");
        jButtonImprime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonImprime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonImprime)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jLabelfleche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet/fleche.gif"))); // NOI18N
        jLabelfleche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelflecheMouseClicked(evt);
            }
        });

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        jTableListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableListe);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFormulaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(725, 725, 725)
                        .addComponent(jLabelfleche))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFormulaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jLabelfleche)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
  //affichage liste des étudiant 
  public void UpdateTable(){
      String sql="SELECT * FROM `etudiant`";
      try{
          PreparedStatement ps =con.prepareStatement(sql);
          ResultSet rs;
          rs =ps.executeQuery();
          
       
          jTableListe.setModel(DbUtils.resultSetToTableModel(rs));
         
      }catch (SQLException e){
          e.printStackTrace();
      }
 
 
    }
 

 
    //affichage la carte d'étudiant 
  public void CarteEtu(){
      String sql ="SELECT *FROM 'etudiant'";
       try{
          PreparedStatement ps =con.prepareStatement(sql);
          ResultSet rs;
          rs =ps.executeQuery();
           
                  
                  
       }catch (SQLException e){
          e.printStackTrace();
          
      }
  }
    
    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jTextFieldMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculeActionPerformed

    private void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomActionPerformed

    private void jTextFieldFiliereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiliereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiliereActionPerformed

    private void jTextFieldAnnee_EtudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnnee_EtudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnnee_EtudeActionPerformed

    private void jTextFieldFaculteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFaculteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFaculteActionPerformed
   
    //button supprimé étudiant
    private void jButtonSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupActionPerformed
       int ligne=jTableListe.getSelectedRow();
        String id= jTableListe.getModel().getValueAt(ligne,0).toString();
        
        String sql="DELETE FROM `etudiant` WHERE id='"+id+"'";
         try{
            PreparedStatement p =con.prepareStatement(sql);
            p.execute();
            JOptionPane.showMessageDialog(null,"étudiant supprimé");
                    jTextFieldNom.setText("");
                    jTextFieldPrenom.setText("");
                    ((JTextField)bdate.getDateEditor().getUiComponent()).setText("");
                    jTextFieldFiliere.setText("");
                    jTextFieldFaculte.setText("");
                    jTextFieldAnnee_Etude.setText("");
                    jTextFieldMatricule.setText("");
                    JLabelphoto.setText("");
                    
                    jLabelNomCarte.setText("");
                    jLabelPrenomCarte.setText("");
                    jLabelDate_naissCarte.setText("");
                    jLabelFiliereCarte.setText("");
                    jLabelFaculteCarte.setText("");
                    jLabelAnnee_etudeCarte.setText("");
                    jLabelMatriculeCarte.setText("");
                    jLabelPhotoCarte.setText("");
                    
                    
            UpdateTable();
         }catch(Exception e){
                  e.printStackTrace();
              }
    }//GEN-LAST:event_jButtonSupActionPerformed
    // label X pour quitter la fenetre
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
      System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked
    // function resizeImage pour Modifiez les photos en fonction de la taille de Label   
    public ImageIcon resizeImage(String imagePath, byte[] pic){
          
        ImageIcon myImage=null;
        if(imagePath !=null)
        {
        myImage=new ImageIcon(imagePath);
        
        }else{
         myImage=new ImageIcon(pic);
        }
                
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(JLabelphoto.getHeight(), JLabelphoto.getWidth(),  Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    } 
    
    //Button Importer pour importez des photos depuis votre bureau
    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
   JFileChooser fchoser=new JFileChooser("C:\\Users\\toshiba\\Documents\\NetBeansProjects\\IHM\\images");
        fchoser.showOpenDialog(null);
        File f=fchoser.getSelectedFile();
        fname=f.getAbsolutePath();
        ImageIcon micon=new ImageIcon(fname);        
        try {
            File image=new File(fname);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream baos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readnum; (readnum=fis.read(buf)) !=-1;)
            {            
                baos.write(buf,0,readnum);                
            }
            imagePth=fname;
            pimage=baos.toByteArray();
            JLabelphoto.setIcon(resizeImage(fname, buf));
        } catch (Exception e) {
        }   
     
        
    }//GEN-LAST:event_jButtonImportActionPerformed
 
    //Button modifier un étudiant
    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        int ligne=jTableListe.getSelectedRow();
        String id= jTableListe.getModel().getValueAt(ligne,0).toString();
        String sql="UPDATE etudiant SET nom = ?,prenom = ?,date_naiss = ?,filiere = ?,faculte = ?,annee_etude = ?,matricule = ? where id = '"+id+"'";
        
        try{
            PreparedStatement p =con.prepareStatement(sql);
            p.setString(1,jTextFieldNom.getText().toString());
            p.setString(2,jTextFieldPrenom.getText().toString());
            p.setString(3,((JTextField)bdate.getDateEditor().getUiComponent()).getText().toString());
            p.setString(4,jTextFieldFiliere.getText().toString());
            p.setString(5,jTextFieldFaculte.getText().toString());
            p.setString(6,jTextFieldAnnee_Etude.getText().toString());
            p.setString(7,jTextFieldMatricule.getText().toString());
          
            p.execute();
           JOptionPane.showMessageDialog(null, "étudiant modifié");
                    jTextFieldNom.setText("");
                    jTextFieldPrenom.setText("");
                    ((JTextField)bdate.getDateEditor().getUiComponent()).setText("");
                    jTextFieldFiliere.setText("");
                    jTextFieldFaculte.setText("");
                    jTextFieldAnnee_Etude.setText("");
                    jTextFieldMatricule.setText("");
                    JLabelphoto.setText("");
                    
                    jLabelNomCarte.setText("");
                    jLabelPrenomCarte.setText("");
                    jLabelDate_naissCarte.setText("");
                    jLabelFiliereCarte.setText("");
                    jLabelFaculteCarte.setText("");
                    jLabelAnnee_etudeCarte.setText("");
                    jLabelMatriculeCarte.setText("");
                    jLabelPhotoCarte.setText("");
                    
                    
                    
            UpdateTable();
                
            
                    
        }catch(Exception e){
                  e.printStackTrace();
              }
    }//GEN-LAST:event_jButtonModActionPerformed
//Buton Ajouter un étudiant
    private void jButtonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutActionPerformed
                    
              String nom=jTextFieldNom.getText();
              String prenom=jTextFieldPrenom.getText();
              String date_naiss=((JTextField)bdate.getDateEditor().getUiComponent()).getText();
              String filiere=jTextFieldFiliere.getText();
              String faculte=jTextFieldFaculte.getText();
              String annee_etude=jTextFieldAnnee_Etude.getText();
              String matricule=jTextFieldMatricule.getText();
              
              try{
                  PreparedStatement ps =con.prepareStatement("INSERT INTO `etudiant`(`nom`, `prenom`, `date_naiss`, `filiere`, `faculte`, `annee_etude`, `matricule`, `photo`) VALUES (?,?,?,?,?,?,?,?)");
                  if(!nom.equals("")&&!prenom.equals("")&&!date_naiss.equals("")&&!filiere.equals("")&&!faculte.equals("")&&!annee_etude.equals("")&&!matricule.equals("")&&!imagePth.equals("")){
                   ps.setString(1,nom);
                    ps.setString(2,prenom);
                    ps.setString(3,date_naiss);
                    ps.setString(4,filiere);
                    ps.setString(5,faculte);
                    ps.setString(6,annee_etude);
                    ps.setString(7,matricule);
                    InputStream img= new FileInputStream(new File(imagePth));
                    ps.setBlob(8,img);
                    
                    jTextFieldNom.setText("");
                    jTextFieldPrenom.setText("");
                    ((JTextField)bdate.getDateEditor().getUiComponent()).setText("");
                    jTextFieldFiliere.setText("");
                    jTextFieldFaculte.setText("");
                    jTextFieldAnnee_Etude.setText("");
                    jTextFieldMatricule.setText("");
                    JLabelphoto.setText("");
                    
                    
                 if(ps.executeUpdate()!=0){
            JOptionPane.showMessageDialog(null,"étudiant ajouté");
            contactIsCreated=true;}
             }else {
            JOptionPane.showMessageDialog(null,"Quelque chose ne va pas");
            contactIsCreated=false;

        }
              }catch(Exception e){
                  //JOptionPane.showMessageDialog(rootPane,e);
              }
              
    }//GEN-LAST:event_jButtonAjoutActionPerformed
    //Button imprimer pour imprimé une carte d'etudiant
    private void jButtonImprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimeActionPerformed
       try {
            Toolkit tkp = jPanelCarte.getToolkit();
    PrintJob pjp = tkp.getPrintJob(this, null, null);
    Graphics g = pjp.getGraphics();
    jPanelCarte.print(g);
    g.dispose();
    pjp.end();
            
        } catch (Exception e) {
        }
            
    }//GEN-LAST:event_jButtonImprimeActionPerformed
    //cette label pour actualiser la liste des étudiants (table de base donnne)
    private void jLabelflecheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelflecheMouseClicked
        UpdateTable();
    }//GEN-LAST:event_jLabelflecheMouseClicked
//Tableau de liste pour cliquer sur chaque étudiant pour afficher ses données
    private void jTableListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListeMouseClicked
        int ligne=jTableListe.getSelectedRow();
        String id= jTableListe.getModel().getValueAt(ligne,0).toString();
        String sql="Select * from etudiant where id ='"+id+"'";
        Image image = null ;
        
        try{
            PreparedStatement ps =con.prepareStatement(sql);
             ResultSet rs;
             rs =ps.executeQuery();
            if(rs.next()){
                    jTextFieldNom.setText(rs.getString("nom"));
                    jTextFieldPrenom.setText(rs.getString("prenom"));
                    ((JTextField)bdate.getDateEditor().getUiComponent()).setText(rs.getString("date_naiss"));
                    jTextFieldFiliere.setText(rs.getString("filiere"));
                    jTextFieldFaculte.setText(rs.getString("faculte"));
                    jTextFieldAnnee_Etude.setText(rs.getString("annee_etude"));
                    jTextFieldMatricule.setText(rs.getString("matricule"));
                    InputStream binaryStream1 = rs.getBinaryStream("photo");
                try {
                    image = ImageIO.read(binaryStream1);
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(Level.SEVERE, null, ex);
                }   
            
                    JLabelphoto.setIcon(new ImageIcon(image));
                    
                   
                   
                    
                    
                    jLabelNomCarte.setText(rs.getString("nom"));
                    jLabelPrenomCarte.setText(rs.getString("prenom"));
                    jLabelDate_naissCarte.setText(rs.getString("date_naiss"));
                    jLabelFiliereCarte.setText(rs.getString("filiere"));
                    jLabelFaculteCarte.setText(rs.getString("faculte"));
                    jLabelAnnee_etudeCarte.setText(rs.getString("annee_etude"));
                    jLabelMatriculeCarte.setText(rs.getString("matricule"));
                InputStream binaryStream = rs.getBinaryStream("photo");
                try {
                    image = ImageIO.read(binaryStream);
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(Level.SEVERE, null, ex);
                }

                    
                    
            }
            
            jLabelPhotoCarte.setIcon(new ImageIcon(image));
        }catch (SQLException e1){
            e1.printStackTrace();
        } 
        
    }//GEN-LAST:event_jTableListeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelphoto;
    private javax.swing.JButton jButtonAjout;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JButton jButtonImprime;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAnnee_Etude;
    private javax.swing.JLabel jLabelAnnee_Etude1;
    private javax.swing.JLabel jLabelAnnee_etudeCarte;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDate_Naiss;
    private javax.swing.JLabel jLabelDate_Naiss1;
    private javax.swing.JLabel jLabelDate_naissCarte;
    private javax.swing.JLabel jLabelFaculte;
    private javax.swing.JLabel jLabelFaculte1;
    private javax.swing.JLabel jLabelFaculteCarte;
    private javax.swing.JLabel jLabelFiliere;
    private javax.swing.JLabel jLabelFiliere1;
    private javax.swing.JLabel jLabelFiliereCarte;
    private javax.swing.JLabel jLabelMatricule;
    private javax.swing.JLabel jLabelMatricule1;
    private javax.swing.JLabel jLabelMatriculeCarte;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNom1;
    private javax.swing.JLabel jLabelNomCarte;
    private javax.swing.JLabel jLabelPhotoCarte;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPrenom1;
    private javax.swing.JLabel jLabelPrenomCarte;
    private javax.swing.JLabel jLabelfleche;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelCarte;
    private javax.swing.JPanel jPanelFormulaire;
    private javax.swing.JPanel jPanelPhoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListe;
    private javax.swing.JTextField jTextFieldAnnee_Etude;
    private javax.swing.JTextField jTextFieldFaculte;
    private javax.swing.JTextField jTextFieldFiliere;
    private javax.swing.JTextField jTextFieldMatricule;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
